name: Ruby on Rails Deployment
on:
  push:
    branches: [main]
  pull_request:
    branches: [development]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Testing test.prochezmoi.com with ssh connection
        uses: appleboy/ssh-action@master
        env:
          POSTGRES_DB: ${{ secrets.TEST_ENV_DB }}
          POSTGRES_HOST: ${{ secrets.REMOTE_HOST_IP }}
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RAILS_ENV: test
        with:
          host: ${{ secrets.REMOTE_HOST_IP }}
          username: ${{ secrets.REMOTE_HOST_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.REMOTE_HOST_PORT }}
          envs: POSTGRES_DB, 
          script: |
            echo "DB NAME $POSTGRES_DB"
            cd /
            cd ${{ secrets.APP_HOMEPATH }} && git clone git@github.com:bafrimpong/vps-github-actions.git
            cd ${{ secrets.APP_HOMEPATH }} && git status
            cd ${{ secrets.APP_HOMEPATH }} && bundle install
            cd ${{ secrets.APP_HOMEPATH }} && bin/rails db:prepare
            cd ${{ secrets.APP_HOMEPATH }} && bin/rails db:migrate
            cd ${{ secrets.APP_HOMEPATH }} && bin/rails db:seed
            cd ${{ secrets.APP_HOMEPATH }} && bin/rails s -p 3001
